### ISSUE TITLE
hello world

### ISSUE THREAD

**Issue by ToasterSticks** [mxchakitty/gameboy-os#1]

**Comment by mxchakitty** [comment]
![ezgif com-gif-maker(63)](https://user-images.githubusercontent.com/68980781/186989655-e784f0d0-4d60-4898-892b-24cfdbf010f5.gif)

**Comment by brewffee** [comment]
![ezgif com-gif-maker(61)](https://user-images.githubusercontent.com/68980781/186989676-1874b734-6478-4ca9-8a0c-ebac8371afa1.gif)

**Comment by ToasterSticks** [comment]
thank you.

**Comment by brewffee** [comment]
meow

**Comment by ToasterSticks** [comment]
is this the new chatting platform?

**Comment by brewffee** [comment]
yeah

**Comment by brewffee** [comment]
discord down

**Comment by ToasterSticks** [comment]
alright

**Comment by ToasterSticks** [comment]
i legit lag less here than on discord with mobile hotspot

**Comment by brewffee** [comment]
![malicious](https://user-images.githubusercontent.com/68980781/186989876-49866734-ed38-400a-8401-55b10e2ef967.png)

**Comment by ToasterSticks** [comment]
siri is best discord bot

**Comment by ToasterSticks** [comment]
undeniably

**Comment by brewffee** [comment]
ermmm ratio ?

**Comment by ToasterSticks** [comment]
no

**Comment by brewffee** [comment]
um .

**Comment by ToasterSticks** [comment]
mochakitty

**Comment by ToasterSticks** [comment]
why mxcha, cringe!

**Comment by brewffee** [comment]
![ezgif com-gif-maker(33)](https://user-images.githubusercontent.com/68980781/186990042-690d4aa2-c214-447e-bdd1-235f06714be4.gif)

**Comment by ToasterSticks** [comment]
me when

**Comment by brewffee** [comment]
![32936590 305_e6180d55c085b5a3592bcadcd1a4e93c](https://user-images.githubusercontent.com/68980781/186990173-fa6a1b58-17f5-435a-9783-91b43b8d0c1e.jpg)

**Comment by ToasterSticks** [comment]
false false

**Comment by brewffee** [comment]
no

**Comment by ToasterSticks** [comment]
ok
